// gen-headers generates c/opcodes.h, c/adapter_types.h, c/message_types.h, and c/mesh_message.h from the Go constants.
// Run via: go generate ./...
// CI verify: go generate ./... && git diff --exit-code c/
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"unicode"

	"github.com/superbrobenji/lattice-protocol/adapter"
	"github.com/superbrobenji/lattice-protocol/message"
	"github.com/superbrobenji/lattice-protocol/opcodes"
)

func main() {
	root := repoRoot()
	must(writeOpcodesHeader(filepath.Join(root, "c", "opcodes.h")))
	must(writeAdapterTypesHeader(filepath.Join(root, "c", "adapter_types.h")))
	must(writeMeshMessageTypesHeader(filepath.Join(root, "c", "message_types.h")))
	must(writeMeshMessageHeader(filepath.Join(root, "c", "mesh_message.h")))
}

func writeOpcodesHeader(path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}

	if _, err := fmt.Fprint(f, `// Code generated by cmd/gen-headers; DO NOT EDIT.
// Source of truth: opcodes/opcodes.go — run "go generate ./..." to regenerate.

#pragma once

/* Lattice mesh protocol opcode constants.
 * Byte 0 of the data payload in MessageTypeSerialCmdBroadcast frames. */

/* Node ↔ server: health reporting */
`); err != nil {
		_ = f.Close()
		return err
	}
	writeCDefByte(f, "OP_HEALTH_REQ", opcodes.OpHealthReq, "server→node: request health; payload: [B0]")
	writeCDefByte(f, "OP_HEALTH_REPORT", opcodes.OpHealthReport, "node(serial)→server: [B1][1B type][6B mac][4B uptime_le]")
	writeCDefByte(f, "OP_NODE_HEALTH", opcodes.OpNodeHealth, "node(non-serial)→server: [B2][1B type][6B mac][4B uptime_le]")
	if _, err := fmt.Fprint(f, "\n/* Server → node: management */\n"); err != nil {
		_ = f.Close()
		return err
	}
	writeCDefByte(f, "OP_NODE_ID_SET", opcodes.OpNodeIdSet, "assign logical node ID")
	writeCDefByte(f, "OP_CONFIG_SET", opcodes.OpConfigSet, "set adapter type; payload: [C1][6B targetMac][1B adapterType]")
	writeCDefByte(f, "OP_TX_POWER_SET", opcodes.OpTxPowerSet, "set TX power preset; payload: [C2][1B: 0=short 1=indoor 2=outdoor]")
	if _, err := fmt.Fprint(f, "\n/* Server → output node: LED/relay commands */\n"); err != nil {
		_ = f.Close()
		return err
	}
	writeCDefByte(f, "OP_LED_SOLID", opcodes.OpLEDSolid, "solid colour: [D0][r,g,b]")
	writeCDefByte(f, "OP_LED_OFF", opcodes.OpLEDOff, "turn LED strip off")
	writeCDefByte(f, "OP_LED_BLINK", opcodes.OpLEDBlink, "blink: [D2][r,g,b,interval_hi,interval_lo]")
	writeCDefByte(f, "OP_RELAY_SET", opcodes.OpRelaySet, "relay state: [D8][0x00=off, 0x01=on]")
	if _, err := fmt.Fprint(f, "\n/* Node → server: acknowledgement */\n"); err != nil {
		_ = f.Close()
		return err
	}
	writeCDefByte(f, "OP_COMMAND_ACK", opcodes.OpCommandAck, "acknowledge a received command")
	return f.Close()
}

func writeAdapterTypesHeader(path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}

	if _, err := fmt.Fprint(f, `// Code generated by cmd/gen-headers; DO NOT EDIT.
// Source of truth: adapter/types.go — run "go generate ./..." to regenerate.

#pragma once

/* Lattice adapter type identifiers.
 * Carried in health report frames and config set commands. */

`); err != nil {
		_ = f.Close()
		return err
	}
	writeCDefInt32(f, "ADAPTER_TYPE_UNKNOWN", adapter.TypeUnknown, "not yet configured")
	writeCDefInt32(f, "ADAPTER_TYPE_SERIAL", adapter.TypeSerial, "serial management (internal)")
	writeCDefInt32(f, "ADAPTER_TYPE_PIR", adapter.TypePIR, "passive infrared motion sensor (INPUT)")
	writeCDefInt32(f, "ADAPTER_TYPE_LED", adapter.TypeLED, "LED strip (OUTPUT)")
	writeCDefInt32(f, "ADAPTER_TYPE_RELAY", adapter.TypeRelay, "relay switch (OUTPUT)")
	return f.Close()
}

func writeMeshMessageTypesHeader(path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	if _, err := fmt.Fprint(f, `// Code generated by cmd/gen-headers; DO NOT EDIT.
// Source of truth: message/types.go — run "go generate ./..." to regenerate.

#pragma once

/* Lattice mesh message type identifiers.
 * Carried in the messageType field of every mesh_message frame. */

typedef uint8_t MeshMessageType;

`); err != nil {
		_ = f.Close()
		return err
	}
	writeCDefUint8("MESH_TYPE_ADAPTER_DATA", message.MeshTypeAdapterData, "node data relayed toward server", f)
	writeCDefUint8("MESH_TYPE_MASTER_BEACON", message.MeshTypeMasterBeacon, "master→mesh: topology beacon", f)
	writeCDefUint8("MESH_TYPE_ENROLLMENT", message.MeshTypeEnrollment, "node→master: enrollment request", f)
	writeCDefUint8("MESH_TYPE_SERIAL_CMD_BROADCAST", message.MeshTypeSerialCmdBroadcast, "server→node: serial command broadcast", f)
	writeCDefUint8("MESH_TYPE_JOIN_ACK", message.MeshTypeJoinAck, "server→node: enrollment approved", f)
	writeCDefUint8("MESH_TYPE_ROUTE_REPORT", message.MeshTypeRouteReport, "node→server: routing path report", f)
	return f.Close()
}

func writeMeshMessageHeader(path string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer func() { _ = f.Close() }()

	if _, err := fmt.Fprint(f, `// Code generated by cmd/gen-headers; DO NOT EDIT.
// Source of truth: message/message.go — run "go generate ./..." to regenerate.

#pragma once
#include <stdint.h>
#include <assert.h>
#include "adapter_types.h"
#include "message_types.h"

`); err != nil {
		return err
	}

	if _, err := fmt.Fprint(f, "typedef struct __attribute__((packed)) {\n"); err != nil {
		return err
	}

	t := reflect.TypeOf(message.MeshMessage{})
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		cType := field.Tag.Get("c")
		cName := pascalToSnake(field.Name)
		// Array types: "uint8_t[6]" → "uint8_t name[6]"
		if idx := strings.Index(cType, "["); idx >= 0 {
			baseType := cType[:idx]
			arraySuffix := cType[idx:]
			if _, err := fmt.Fprintf(f, "    %-16s %s%s;\n", baseType, cName, arraySuffix); err != nil {
				return err
			}
		} else {
			if _, err := fmt.Fprintf(f, "    %-16s %s;\n", cType, cName); err != nil {
				return err
			}
		}
	}

	if _, err := fmt.Fprintf(f, "} mesh_message;\n\nstatic_assert(sizeof(mesh_message) == %d, \"mesh_message size changed — update server proto\");\n", message.WireSize); err != nil {
		return err
	}
	return nil
}

// pascalToSnake converts PascalCase to snake_case. "OriginMacAddress" → "origin_mac_address".
func pascalToSnake(s string) string {
	var out []rune
	for i, r := range s {
		if unicode.IsUpper(r) && i > 0 {
			out = append(out, '_')
		}
		out = append(out, unicode.ToLower(r))
	}
	return string(out)
}

// protoFieldName returns the proto3 field name for a Go field.
// Uses the 4th element of the proto tag if present, otherwise lowerCamelCase of Go name.
func protoFieldName(goName, protoTag string) string {
	parts := strings.Split(protoTag, ",")
	if len(parts) >= 4 && parts[3] != "" {
		return parts[3]
	}
	// lowerCamelCase: "OriginMacAddress" → "originMacAddress"
	runes := []rune(goName)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

func writeCDefUint8(name string, val uint8, comment string, f *os.File) {
	_, err := fmt.Fprintf(f, "#define %-32s ((MeshMessageType)%d)  /* %s */\n", name, val, comment)
	must(err)
}

func writeCDefByte(f *os.File, name string, val byte, comment string) {
	_, err := fmt.Fprintf(f, "#define %-20s 0x%02X  /* %s */\n", name, val, comment)
	must(err)
}

func writeCDefInt32(f *os.File, name string, val int32, comment string) {
	_, err := fmt.Fprintf(f, "#define %-24s %d  /* %s */\n", name, val, comment)
	must(err)
}

func repoRoot() string {
	// The generator lives at cmd/gen-headers/main.go; repo root is two levels up.
	exe, err := os.Executable()
	must(err)
	// During `go run`, the executable is in a temp dir — use the working directory instead.
	wd, err := os.Getwd()
	must(err)
	_ = exe
	// Walk up until we find go.mod
	dir := wd
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			fmt.Fprintln(os.Stderr, "gen-headers: could not find repo root (no go.mod found)")
			os.Exit(1)
		}
		dir = parent
	}
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen-headers:", err)
		os.Exit(1)
	}
}
