// Code generated by cmd/gen-headers; DO NOT EDIT.
// Source of truth: message/message.go — run "go generate ./..." to regenerate.

#ifndef LATTICE_MESH_MESSAGE_H
#define LATTICE_MESH_MESSAGE_H

#pragma once
#include <stdint.h>
#include <assert.h>
#include "adapter_types.h"
#include "message_types.h"

typedef struct __attribute__((packed)) {
    uint8_t          proto_version;
    uint8_t          message_type;
    int32_t          data_type;
    uint8_t          origin_mac_address[6];
    uint8_t          target_mac_address[6];
    uint8_t          last_hop_mac_address[6];
    uint8_t          data[64];
    uint8_t          hop_count;
    uint32_t         epoch_num;
    uint16_t         seq_num;
    uint8_t          enrollment_public_key[32];
    uint8_t          route_len;
    uint8_t          route_path[48];
    uint8_t          auth_tag[16];
    uint8_t          auth_path[8];
} mesh_message;

static_assert(sizeof(mesh_message) == 200, "mesh_message size changed — update server proto");

#endif /* LATTICE_MESH_MESSAGE_H */
