// Code generated by cmd/gen-headers; DO NOT EDIT.
// Source of truth: message/types.go — run "go generate ./..." to regenerate.

#pragma once

/* Lattice mesh message type identifiers.
 * Carried in the messageType field of every mesh_message frame. */

typedef uint8_t MeshMessageType;

#define MESH_TYPE_ADAPTER_DATA           ((MeshMessageType)0)  /* node data relayed toward server */
#define MESH_TYPE_MASTER_BEACON          ((MeshMessageType)1)  /* master→mesh: topology beacon */
#define MESH_TYPE_ENROLLMENT             ((MeshMessageType)2)  /* node→master: enrollment request */
#define MESH_TYPE_SERIAL_CMD_BROADCAST   ((MeshMessageType)3)  /* server→node: serial command broadcast */
#define MESH_TYPE_JOIN_ACK               ((MeshMessageType)4)  /* server→node: enrollment approved */
#define MESH_TYPE_ROUTE_REPORT           ((MeshMessageType)5)  /* node→server: routing path report */
